const units = {
  "Abel": new Unit({
    "name": "Abel",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Abel:_The_Panther"
  }),
  "Alfonse": new Unit({
    "name": "Alfonse",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Alfonse:_Prince_of_Askr"
  }),
  "HF-Alfonse": new Unit({
    "name": "HF-Alfonse",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Alfonse:_Spring_Prince"
  }),
  "Alm": new Unit({
    "name": "Alm",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Alm:_Hero_of_Prophecy"
  }),
  "Amelia": new Unit({
    "name": "Amelia",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 173,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Amelia:_Rose_of_the_War"
  }),
  "Anna": new Unit({
    "name": "Anna",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Anna:_Commander"
  }),
  "Arden": new Unit({
    "name": "Arden",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Arden:_Strong_and_Tough"
  }),
  "Ares": new Unit({
    "name": "Ares",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Ares:_Black_Knight"
  }),
  "Arthur": new Unit({
    "name": "Arthur",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Arthur:_Hapless_Hero"
  }),
  "Arvis": new Unit({
    "name": "Arvis",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Arvis:_Emperor_of_Flame"
  }),
  "Athena": new Unit({
    "name": "Athena",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Athena:_Borderland_Sword"
  }),
  "Ayra": new Unit({
    "name": "Ayra",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ayra:_Astra%27s_Wielder"
  }),
  "Azama": new Unit({
    "name": "Azama",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Azama:_Carefree_Monk"
  }),
  "Azura": new Unit({
    "name": "Azura",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Azura:_Lady_of_the_Lake"
  }),
  "NY-Azura": new Unit({
    "name": "NY-Azura",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Azura:_Celebratory_Spirit"
  }),
  "PA-Azura": new Unit({
    "name": "PA-Azura",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Azura:_Lady_of_Ballads"
  }),
  "Barst": new Unit({
    "name": "Barst",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Barst:_The_Hatchet"
  }),
  "Bartre": new Unit({
    "name": "Bartre",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Bartre:_Fearless_Warrior"
  }),
  "Berkut": new Unit({
    "name": "Berkut",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Berkut:_Prideful_Prince"
  }),
  "Beruka": new Unit({
    "name": "Beruka",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Beruka:_Quiet_Assassin"
  }),
  "Black-Knight": new Unit({
    "name": "Black-Knight",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Black_Knight:_Sinister_General"
  }),
  "Boey": new Unit({
    "name": "Boey",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Boey:_Skillful_Survivor"
  }),
  "Caeda": new Unit({
    "name": "Caeda",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Caeda:_Talys%27s_Heart"
  }),
  "B-Caeda": new Unit({
    "name": "B-Caeda",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Caeda:_Talys%27s_Bride"
  }),
  "Cain": new Unit({
    "name": "Cain",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Cain:_The_Bull"
  }),
  "Camilla": new Unit({
    "name": "Camilla",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Camilla:_Bewitching_Beauty"
  }),
  "NY-Camilla": new Unit({
    "name": "NY-Camilla",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Camilla:_Holiday_Traveler"
  }),
  "S-Camilla": new Unit({
    "name": "S-Camilla",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Camilla:_Spring_Princess"
  }),
  "SS-Camilla": new Unit({
    "name": "SS-Camilla",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Camilla:_Tropical_Beauty"
  }),
  "Camus": new Unit({
    "name": "Camus",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Camus:_Sable_Knight"
  }),
  "Canas": new Unit({
    "name": "Canas",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Canas:_Wisdom_Seeker"
  }),
  "Catria": new Unit({
    "name": "Catria",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Catria:_Middle_Whitewing"
  }),
  "S-Catria": new Unit({
    "name": "S-Catria",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Catria:_Spring_Whitewing"
  }),
  "Cecilia": new Unit({
    "name": "Cecilia",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Cecilia:_Etrurian_General"
  }),
  "Celica": new Unit({
    "name": "Celica",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Celica:_Caring_Princess"
  }),
  "BH-Celica": new Unit({
    "name": "BH-Celica",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Celica:_Warrior_Priestess"
  }),
  "FH-Celica": new Unit({
    "name": "FH-Celica",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Celica:_Imprisoned_Soul"
  }),
  "B-Charlotte": new Unit({
    "name": "B-Charlotte",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Charlotte:_Money_Maiden"
  }),
  "Cherche": new Unit({
    "name": "Cherche",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Cherche:_Wyvern_Friend"
  }),
  "Chrom": new Unit({
    "name": "Chrom",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Chrom:_Exalted_Prince"
  }),
  "NY-Chrom": new Unit({
    "name": "NY-Chrom",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Chrom:_Gifted_Leader"
  }),
  "K-Chrom": new Unit({
    "name": "K-Chrom",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Chrom:_Knight_Exalt"
  }),
  "S-Chrom": new Unit({
    "name": "S-Chrom",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Chrom:_Spring_Exalt"
  }),
  "Clair": new Unit({
    "name": "Clair",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Clair:_Highborn_Flier"
  }),
  "Clarine": new Unit({
    "name": "Clarine",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Clarine:_Refined_Noble"
  }),
  "Clarisse": new Unit({
    "name": "Clarisse",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Clarisse:_Sniper_in_the_Dark"
  }),
  "Clive": new Unit({
    "name": "Clive",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Clive:_Idealistic_Knight"
  }),
  "Cordelia": new Unit({
    "name": "Cordelia",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Cordelia:_Knight_Paragon"
  }),
  "S-Cordelia": new Unit({
    "name": "S-Cordelia",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Cordelia:_Knight_Paradise"
  }),
  "B-Cordelia": new Unit({
    "name": "B-Cordelia",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Cordelia:_Perfect_Bride"
  }),
  "F-Corrin": new Unit({
    "name": "F-Corrin",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Corrin:_Fateful_Princess"
  }),
  "M-Corrin": new Unit({
    "name": "M-Corrin",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Corrin:_Fateful_Prince"
  }),
  "NY-Corrin": new Unit({
    "name": "NY-Corrin",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Corrin:_Enjoying_Tradition"
  }),
  "S-Corrin": new Unit({
    "name": "S-Corrin",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Corrin:_Novice_Vacationer"
  }),
  "Deirdre": new Unit({
    "name": "Deirdre",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Deirdre:_Lady_of_the_Forest"
  }),
  "Delthea": new Unit({
    "name": "Delthea",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Delthea:_Free_Spirit"
  }),
  "Donnel": new Unit({
    "name": "Donnel",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Donnel:_Village_Hero"
  }),
  "Dorcas": new Unit({
    "name": "Dorcas",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Dorcas:_Serene_Warrior"
  }),
  "Draug": new Unit({
    "name": "Draug",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Draug:_Gentle_Giant"
  }),
  "Effie": new Unit({
    "name": "Effie",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 168,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Effie:_Army_of_One"
  }),
  "Eirika": new Unit({
    "name": "Eirika",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Eirika:_Restoration_Lady"
  }),
  "F-Eirika": new Unit({
    "name": "F-Eirika",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Eirika:_Anamnesis_Lady"
  }),
  "Eldigan": new Unit({
    "name": "Eldigan",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Eldigan:_Lionheart"
  }),
  "Elincia": new Unit({
    "name": "Elincia",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Elincia:_Lost_Princess"
  }),
  "PA-Elincia": new Unit({
    "name": "PA-Elincia",
    "moveType": "infantry",
    "weaponType": "greenBow",
    "bst": 139,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Elincia:_Estival_Princess"
  }),
  "Elise": new Unit({
    "name": "Elise",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Elise:_Budding_Flower"
  }),
  "S-Elise": new Unit({
    "name": "S-Elise",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Elise:_Tropical_Flower"
  }),
  "LA-Eliwood": new Unit({
    "name": "LA-Eliwood",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Eliwood:_Devoted_Love"
  }),
  "Eliwood": new Unit({
    "name": "Eliwood",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Eliwood:_Knight_of_Lycia"
  }),
  "Ephraim": new Unit({
    "name": "Ephraim",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ephraim:_Restoration_Lord"
  }),
  "BH-Ephraim": new Unit({
    "name": "BH-Ephraim",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ephraim:_Sacred_Twin_Lord"
  }),
  "L-Ephraim": new Unit({
    "name": "L-Ephraim",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ephraim:_Legendary_Lord"
  }),
  "Est": new Unit({
    "name": "Est",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Est:_Junior_Whitewing"
  }),
  "Fae": new Unit({
    "name": "Fae",
    "moveType": "infantry",
    "weaponType": "greenBreath",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Fae:_Divine_Dragon"
  }),
  "Faye": new Unit({
    "name": "Faye",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Faye:_Devoted_Heart"
  }),
  "Felicia": new Unit({
    "name": "Felicia",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Felicia:_Maid_Mayhem"
  }),
  "Finn": new Unit({
    "name": "Finn",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Finn:_Lance_of_Legend"
  }),
  "Fir": new Unit({
    "name": "Fir",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Fir:_Sword_Student"
  }),
  "Fjorm": new Unit({
    "name": "Fjorm",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Fjorm:_Princess_of_Ice"
  }),
  "Florina": new Unit({
    "name": "Florina",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Florina:_Lovely_Flier"
  }),
  "Frederick": new Unit({
    "name": "Frederick",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 153,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Frederick:_Polite_Knight"
  }),
  "S-Frederick": new Unit({
    "name": "S-Frederick",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Frederick:_Horizon_Watcher"
  }),
  "Gaius": new Unit({
    "name": "Gaius",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Gaius:_Candy_Stealer"
  }),
  "S-Gaius": new Unit({
    "name": "S-Gaius",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Gaius:_Thief_Exposed"
  }),
  "Genny": new Unit({
    "name": "Genny",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Genny:_Endearing_Ally"
  }),
  "Gerome": new Unit({
    "name": "Gerome",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 161,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Gerome:_Masked_Rider"
  }),
  "Gordin": new Unit({
    "name": "Gordin",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Gordin:_Altean_Archer"
  }),
  "Gray": new Unit({
    "name": "Gray",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Gray:_Wry_Comrade"
  }),
  "Gunnthra": new Unit({
    "name": "Gunnthra",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Gunnthr%C3%A1:_Voice_of_Dreams"
  }),
  "Gunter": new Unit({
    "name": "Gunter",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Gunter:_Inveterate_Soldier"
  }),
  "Gwendolyn": new Unit({
    "name": "Gwendolyn",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 169,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Gwendolyn:_Adorable_Knight"
  }),
  "Hana": new Unit({
    "name": "Hana",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Hana:_Focused_Samurai"
  }),
  "Hardin": new Unit({
    "name": "Hardin",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Hardin:_Dark_Emperor"
  }),
  "Hawkeye": new Unit({
    "name": "Hawkeye",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Hawkeye:_Desert_Guardian"
  }),
  "Hector": new Unit({
    "name": "Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 168,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Hector:_General_of_Ostia"
  }),
  "BH-Hector": new Unit({
    "name": "BH-Hector",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2270,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Hector:_Brave_Warrior"
  }),
  "LA-Hector": new Unit({
    "name": "LA-Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 173,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Hector:_Just_Here_to_Fight"
  }),
  "L-Hector": new Unit({
    "name": "L-Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Hector:_Marquess_of_Ostia"
  }),
  "Henry": new Unit({
    "name": "Henry",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Henry:_Twisted_Mind"
  }),
  "H-Henry": new Unit({
    "name": "H-Henry",
    "moveType": "armor",
    "weaponType": "greenTome",
    "bst": 165,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Henry:_Happy_Vampire"
  }),
  "Hinata": new Unit({
    "name": "Hinata",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Hinata:_Wild_Samurai"
  }),
  "Hinoka": new Unit({
    "name": "Hinoka",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Hinoka:_Warrior_Princess"
  }),
  "BSW-Hinoka": new Unit({
    "name": "BSW-Hinoka",
    "moveType": "flier",
    "weaponType": "bow",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Hinoka:_Blue_Sky_Warrior"
  }),
  "Ike": new Unit({
    "name": "Ike",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ike:_Young_Mercenary"
  }),
  "BH-Ike": new Unit({
    "name": "BH-Ike",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ike:_Brave_Mercenary"
  }),
  "L-Ike": new Unit({
    "name": "L-Ike",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ike:_Vanguard_Legend"
  }),
  "Inigo": new Unit({
    "name": "Inigo",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Inigo:_Indigo_Dancer"
  }),
  "Innes": new Unit({
    "name": "Innes",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Innes:_Regal_Strategician"
  }),
  "S-Innes": new Unit({
    "name": "S-Innes",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Innes:_Flawless_Form"
  }),
  "Ishtar": new Unit({
    "name": "Ishtar",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ishtar:_Thunder_Goddess"
  }),
  "Jaffar": new Unit({
    "name": "Jaffar",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Jaffar:_Angel_of_Death"
  }),
  "Jagen": new Unit({
    "name": "Jagen",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Jagen:_Veteran_Knight"
  }),
  "Jakob": new Unit({
    "name": "Jakob",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Jakob:_Devoted_Servant"
  }),
  "H-Jakob": new Unit({
    "name": "H-Jakob",
    "moveType": "armor",
    "weaponType": "bow",
    "bst": 165,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Jakob:_Devoted_Monster"
  }),
  "Jeorge": new Unit({
    "name": "Jeorge",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Jeorge:_Perfect_Shot"
  }),
  "Joshua": new Unit({
    "name": "Joshua",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Joshua:_Tempest_King"
  }),
  "Julia": new Unit({
    "name": "Julia",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Julia:_Naga%27s_Blood"
  }),
  "Julius": new Unit({
    "name": "Julius",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Julius:_Scion_of_Darkness"
  }),
  "Kagero": new Unit({
    "name": "Kagero",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Kagero:_Honorable_Ninja"
  }),
  "S-Kagero": new Unit({
    "name": "S-Kagero",
    "moveType": "flier",
    "weaponType": "dagger",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Kagero:_Spring_Ninja"
  }),
  "F-Kana": new Unit({
    "name": "F-Kana",
    "moveType": "infantry",
    "weaponType": "greenBreath",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Kana:_Dragon_Princess"
  }),
  "M-Kana": new Unit({
    "name": "M-Kana",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Kana:_Dragon_Spawn"
  }),
  "Karel": new Unit({
    "name": "Karel",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Karel:_Sword_Demon"
  }),
  "Karla": new Unit({
    "name": "Karla",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Karla:_Sword_Vassal"
  }),
  "Katarina": new Unit({
    "name": "Katarina",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Katarina:_Wayward_One"
  }),
  "Kaze": new Unit({
    "name": "Kaze",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Kaze:_Easygoing_Ninja"
  }),
  "Klein": new Unit({
    "name": "Klein",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Klein:_Silver_Nobleman"
  }),
  "L-Arachel": new Unit({
    "name": "L-Arachel",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "L%27Arachel:_Princess_of_Light"
  }),
  "Lachesis": new Unit({
    "name": "Lachesis",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Lachesis:_Lionheart%27s_Sister"
  }),
  "Laslow": new Unit({
    "name": "Laslow",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Laslow:_Dancing_Duelist"
  }),
  "Legault": new Unit({
    "name": "Legault",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Legault:_The_Hurricane"
  }),
  "Legion": new Unit({
    "name": "Legion",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Legion:_Masked_Maniac"
  }),
  "Leif": new Unit({
    "name": "Leif",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Leif:_Prince_of_Leonster"
  }),
  "Lene": new Unit({
    "name": "Lene",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lene:_Yearning_Dancer"
  }),
  "Leo": new Unit({
    "name": "Leo",
    "moveType": "cavalry",
    "weaponType": "redTome",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Leo:_Sorcerous_Prince"
  }),
  "S-Leo": new Unit({
    "name": "S-Leo",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Leo:_Seashore%27s_Prince"
  }),
  "Leon": new Unit({
    "name": "Leon",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Leon:_True_of_Heart"
  }),
  "Libra": new Unit({
    "name": "Libra",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Libra:_Fetching_Friar"
  }),
  "Lilina": new Unit({
    "name": "Lilina",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Lilina:_Delightful_Noble"
  }),
  "LA-Lilina": new Unit({
    "name": "LA-Lilina",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Lilina:_Blush_of_Youth"
  }),
  "Linde": new Unit({
    "name": "Linde",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Linde:_Light_Mage"
  }),
  "S-Linde": new Unit({
    "name": "S-Linde",
    "moveType": "cavalry",
    "weaponType": "dagger",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Linde:_Summer_Rays"
  }),
  "Linus": new Unit({
    "name": "Linus",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Linus:_Mad_Dog"
  }),
  "Lissa": new Unit({
    "name": "Lissa",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Lissa:_Pure_Joy"
  }),
  "NY-Lissa": new Unit({
    "name": "NY-Lissa",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Lissa:_Sprightly_Cleric"
  }),
  "Lloyd": new Unit({
    "name": "Lloyd",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Lloyd:_White_Wolf"
  }),
  "Lon-qu": new Unit({
    "name": "Lon-qu",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Lon%27qu:_Solitary_Blade"
  }),
  "Lucina": new Unit({
    "name": "Lucina",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lucina:_Future_Witness"
  }),
  "BH-Lucina": new Unit({
    "name": "BH-Lucina",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lucina:_Brave_Princess"
  }),
  "L-Lucina": new Unit({
    "name": "L-Lucina",
    "moveType": "infantry",
    "weaponType": "blueBow",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2320,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lucina:_Glorious_Archer"
  }),
  "S-Lucina": new Unit({
    "name": "S-Lucina",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Lucina:_Spring_Exalt"
  }),
  "Lucius": new Unit({
    "name": "Lucius",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Lucius:_The_Light"
  }),
  "Lukas": new Unit({
    "name": "Lukas",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Lukas:_Sharp_Soldier"
  }),
  "Luke": new Unit({
    "name": "Luke",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Luke:_Rowdy_Squire"
  }),
  "Lute": new Unit({
    "name": "Lute",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lute:_Prodigy"
  }),
  "Lyn": new Unit({
    "name": "Lyn",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lyn:_Lady_of_the_Plains"
  }),
  "B-Lyn": new Unit({
    "name": "B-Lyn",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Lyn:_Bride_of_the_Plains"
  }),
  "BH-Lyn": new Unit({
    "name": "BH-Lyn",
    "moveType": "cavalry",
    "weaponType": "bow",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lyn:_Brave_Lady"
  }),
  "L-Lyn": new Unit({
    "name": "L-Lyn",
    "moveType": "infantry",
    "weaponType": "greenBow",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Lyn:_Lady_of_the_Wind"
  }),
  "LA-Lyn": new Unit({
    "name": "LA-Lyn",
    "moveType": "armor",
    "weaponType": "blueTome",
    "bst": 165,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Lyn:_Wind%27s_Embrace"
  }),
  "Lyon": new Unit({
    "name": "Lyon",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 152,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Lyon:_Shadow_Prince"
  }),
  "Mae": new Unit({
    "name": "Mae",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Mae:_Bundle_of_Energy"
  }),
  "Maria": new Unit({
    "name": "Maria",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Maria:_Minerva%27s_Sister"
  }),
  "Maribelle": new Unit({
    "name": "Maribelle",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Maribelle:_Dire_Damsel"
  }),
  "Marisa": new Unit({
    "name": "Marisa",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Marisa:_Crimson_Flash"
  }),
  "Marth": new Unit({
    "name": "Marth",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Marth:_Altean_Prince"
  }),
  "B-Marth": new Unit({
    "name": "B-Marth",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Marth:_Altean_Groom"
  }),
  "L-Marth": new Unit({
    "name": "L-Marth",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Marth:_Hero-King"
  }),
  "M-Marth": new Unit({
    "name": "M-Marth",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 8,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Marth:_Enigmatic_Blade"
  }),
  "Mathilda": new Unit({
    "name": "Mathilda",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Mathilda:_Legendary_Knight"
  }),
  "Matthew": new Unit({
    "name": "Matthew",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Matthew:_Faithful_Spy"
  }),
  "Merric": new Unit({
    "name": "Merric",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Merric:_Wind_Mage"
  }),
  "Mia": new Unit({
    "name": "Mia",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Mia:_Lady_of_Blades"
  }),
  "Micaiah": new Unit({
    "name": "Micaiah",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2320,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Micaiah:_Priestess_of_Dawn"
  }),
  "PA-Micaiah": new Unit({
    "name": "PA-Micaiah",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 139,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Micaiah:_Summer%27s_Dawn"
  }),
  "Michalis": new Unit({
    "name": "Michalis",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Michalis:_Ambitious_King"
  }),
  "Minerva": new Unit({
    "name": "Minerva",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Minerva:_Red_Dragoon"
  }),
  "Mist": new Unit({
    "name": "Mist",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Mist:_Helpful_Sister"
  }),
  "F-Morgan": new Unit({
    "name": "F-Morgan",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Morgan:_Lass_from_Afar"
  }),
  "M-Morgan": new Unit({
    "name": "M-Morgan",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Morgan:_Lad_from_Afar"
  }),
  "Myrrh": new Unit({
    "name": "Myrrh",
    "moveType": "flier",
    "weaponType": "greenBreath",
    "bst": 167,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Myrrh:_Great_Dragon"
  }),
  "Nanna": new Unit({
    "name": "Nanna",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Nanna:_Nordion_Princess"
  }),
  "Narcian": new Unit({
    "name": "Narcian",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 6,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Narcian:_Wyvern_General"
  }),
  "Navarre": new Unit({
    "name": "Navarre",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 6,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Navarre:_Scarlet_Sword"
  }),
  "Nephenee": new Unit({
    "name": "Nephenee",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Nephenee:_Fierce_Halberdier"
  }),
  "Niles": new Unit({
    "name": "Niles",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Niles:_Cruel_to_Be_Kind"
  }),
  "Ninian": new Unit({
    "name": "Ninian",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ninian:_Oracle_of_Destiny"
  }),
  "B-Ninian": new Unit({
    "name": "B-Ninian",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 140,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Ninian:_Bright-Eyed_Bride"
  }),
  "Nino": new Unit({
    "name": "Nino",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Nino:_Pious_Mage"
  }),
  "P-Nino": new Unit({
    "name": "P-Nino",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Nino:_Pale_Flower"
  }),
  "Noire": new Unit({
    "name": "Noire",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Noire:_Shade_Seeker"
  }),
  "Nowi": new Unit({
    "name": "Nowi",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Nowi:_Eternal_Youth"
  }),
  "H-Nowi": new Unit({
    "name": "H-Nowi",
    "moveType": "flier",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Nowi:_Eternal_Witch"
  }),
  "Oboro": new Unit({
    "name": "Oboro",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Oboro:_Fierce_Fighter"
  }),
  "Odin": new Unit({
    "name": "Odin",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Odin:_Potent_Force"
  }),
  "Ogma": new Unit({
    "name": "Ogma",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Ogma:_Loyal_Blade"
  }),
  "Oliver": new Unit({
    "name": "Oliver",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Oliver:_Admirer_of_Beauty"
  }),
  "Olivia": new Unit({
    "name": "Olivia",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Olivia:_Blushing_Beauty"
  }),
  "PA-Olivia": new Unit({
    "name": "PA-Olivia",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 140,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Olivia:_Festival_Dancer"
  }),
  "F-Olivia": new Unit({
    "name": "F-Olivia",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Olivia:_Sky-High_Dancer"
  }),
  "Olwen": new Unit({
    "name": "Olwen",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Olwen:_Blue_Mage_Knight"
  }),
  "R-Olwen": new Unit({
    "name": "R-Olwen",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Olwen:_Righteous_Knight"
  }),
  "Oscar": new Unit({
    "name": "Oscar",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Oscar:_Agile_Horseman"
  }),
  "Palla": new Unit({
    "name": "Palla",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Palla:_Eldest_Whitewing"
  }),
  "Peri": new Unit({
    "name": "Peri",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Peri:_Playful_Slayer"
  }),
  "Priscilla": new Unit({
    "name": "Priscilla",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Priscilla:_Delicate_Princess"
  }),
  "Raigh": new Unit({
    "name": "Raigh",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Raigh:_Dark_Child"
  }),
  "Raven": new Unit({
    "name": "Raven",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Raven:_Peerless_Fighter"
  }),
  "Rebecca": new Unit({
    "name": "Rebecca",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Rebecca:_Wildflower"
  }),
  "Reinhardt": new Unit({
    "name": "Reinhardt",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Reinhardt:_Thunder%27s_Fist"
  }),
  "S-Reinhardt": new Unit({
    "name": "S-Reinhardt",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Reinhardt:_Thunder%27s_Sword"
  }),
  "Rhajat": new Unit({
    "name": "Rhajat",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Rhajat:_Black_Magician"
  }),
  "F-Grima": new Unit({
    "name": "F-Grima",
    "moveType": "flier",
    "weaponType": "breath",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Robin:_Fell_Vessel"
  }),
  "M-Grima": new Unit({
    "name": "M-Grima",
    "moveType": "armor",
    "weaponType": "greenBreath",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Robin:_Fell_Reincarnation"
  }),
  "F-Robin": new Unit({
    "name": "F-Robin",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 6,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Robin:_Mystery_Tactician"
  }),
  "M-Robin": new Unit({
    "name": "M-Robin",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Robin:_High_Deliverer"
  }),
  "SF-Robin": new Unit({
    "name": "SF-Robin",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Robin:_Seaside_Tactician"
  }),
  "NYM-Robin": new Unit({
    "name": "NYM-Robin",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Robin:_Festive_Tactician"
  }),
  "Roderick": new Unit({
    "name": "Roderick",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Roderick:_Steady_Squire"
  }),
  "Roy": new Unit({
    "name": "Roy",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Roy:_Young_Lion"
  }),
  "BH-Roy": new Unit({
    "name": "BH-Roy",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Roy:_Brave_Lion"
  }),
  "LA-Roy": new Unit({
    "name": "LA-Roy",
    "moveType": "cavalry",
    "weaponType": "bow",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Roy:_Youthful_Gifts"
  }),
  "Ryoma": new Unit({
    "name": "Ryoma",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ryoma:_Peerless_Samurai"
  }),
  "L-Ryoma": new Unit({
    "name": "L-Ryoma",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Ryoma:_Supreme_Samurai"
  }),
  "PA-Ryoma": new Unit({
    "name": "PA-Ryoma",
    "moveType": "infantry",
    "weaponType": "blueBow",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Ryoma:_Dancing_Samurai"
  }),
  "Saber": new Unit({
    "name": "Saber",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Saber:_Driven_Mercenary"
  }),
  "Saias": new Unit({
    "name": "Saias",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Saias:_Bishop_of_Flame"
  }),
  "Saizo": new Unit({
    "name": "Saizo",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Saizo:_Angry_Ninja"
  }),
  "Sakura": new Unit({
    "name": "Sakura",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Sakura:_Loving_Priestess"
  }),
  "H-Sakura": new Unit({
    "name": "H-Sakura",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Sakura:_Gentle_Nekomata"
  }),
  "Sanaki": new Unit({
    "name": "Sanaki",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Sanaki:_Begnion%27s_Apostle"
  }),
  "B-Sanaki": new Unit({
    "name": "B-Sanaki",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Sanaki:_Apostle_in_White"
  }),
  "Selena": new Unit({
    "name": "Selena",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Selena:_Cutting_Wit"
  }),
  "Seliph": new Unit({
    "name": "Seliph",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Seliph:_Heir_of_Light"
  }),
  "Serra": new Unit({
    "name": "Serra",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Serra:_Outspoken_Cleric"
  }),
  "Seth": new Unit({
    "name": "Seth",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Seth:_Silver_Knight"
  }),
  "Setsuna": new Unit({
    "name": "Setsuna",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Setsuna:_Absent_Archer"
  }),
  "Shanna": new Unit({
    "name": "Shanna",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Shanna:_Sprightly_Flier"
  }),
  "Sharena": new Unit({
    "name": "Sharena",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Sharena:_Princess_of_Askr"
  }),
  "S-Sharena": new Unit({
    "name": "S-Sharena",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Sharena:_Spring_Princess"
  }),
  "Sheena": new Unit({
    "name": "Sheena",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 169,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Sheena:_Princess_of_Gra"
  }),
  "Shigure": new Unit({
    "name": "Shigure",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Shigure:_Dark_Sky_Singer"
  }),
  "PA-Shigure": new Unit({
    "name": "PA-Shigure",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 139,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Shigure:_Uplifting_Artist"
  }),
  "Shiro": new Unit({
    "name": "Shiro",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Shiro:_Raw_Talent"
  }),
  "Siegbert": new Unit({
    "name": "Siegbert",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Siegbert:_Future_King"
  }),
  "Sigurd": new Unit({
    "name": "Sigurd",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 159,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Sigurd:_Holy_Knight"
  }),
  "Soleil": new Unit({
    "name": "Soleil",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Soleil:_Adorable_Adorer"
  }),
  "Sonya": new Unit({
    "name": "Sonya",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Sonya:_Vengeful_Mage"
  }),
  "Sophia": new Unit({
    "name": "Sophia",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Sophia:_Nabata_Prophet"
  }),
  "Soren": new Unit({
    "name": "Soren",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Soren:_Shrewd_Strategist"
  }),
  "Sothe": new Unit({
    "name": "Sothe",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Sothe:_Zephyr"
  }),
  "Stahl": new Unit({
    "name": "Stahl",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Stahl:_Viridian_Knight"
  }),
  "Subaki": new Unit({
    "name": "Subaki",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Subaki:_Perfect_Expert"
  }),
  "Sully": new Unit({
    "name": "Sully",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Sully:_Crimson_Knight"
  }),
  "Sumia": new Unit({
    "name": "Sumia",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Sumia:_Maid_of_Flowers"
  }),
  "Tailtiu": new Unit({
    "name": "Tailtiu",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Tailtiu:_Thunder_Noble"
  }),
  "Takumi": new Unit({
    "name": "Takumi",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Takumi:_Wild_Card"
  }),
  "F-Takumi": new Unit({
    "name": "F-Takumi",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Takumi:_Empty_Vessel"
  }),
  "NY-Takumi": new Unit({
    "name": "NY-Takumi",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 152,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Takumi:_Prince_of_Soup"
  }),
  "S-Takumi": new Unit({
    "name": "S-Takumi",
    "moveType": "flier",
    "weaponType": "bow",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Takumi:_Prince_at_Play"
  }),
  "Tana": new Unit({
    "name": "Tana",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Tana:_Winged_Princess"
  }),
  "S-Tana": new Unit({
    "name": "S-Tana",
    "moveType": "flier",
    "weaponType": "redTome",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Tana:_Noble_and_Nimble"
  }),
  "Tharja": new Unit({
    "name": "Tharja",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Tharja:_Dark_Shadow"
  }),
  "B-Tharja": new Unit({
    "name": "B-Tharja",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Tharja:_Obsessive_Bride"
  }),
  "NY-Tharja": new Unit({
    "name": "NY-Tharja",
    "moveType": "armor",
    "weaponType": "redTome",
    "bst": 165,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Tharja:_%22Normal_Girl%22"
  }),
  "A-Tiki": new Unit({
    "name": "A-Tiki",
    "moveType": "infantry",
    "weaponType": "redBreath",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Tiki:_Naga%27s_Voice"
  }),
  "Y-Tiki": new Unit({
    "name": "Y-Tiki",
    "moveType": "infantry",
    "weaponType": "redBreath",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Tiki:_Dragon_Scion"
  }),
  "SA-Tiki": new Unit({
    "name": "SA-Tiki",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Tiki:_Summering_Scion"
  }),
  "SY-Tiki": new Unit({
    "name": "SY-Tiki",
    "moveType": "flier",
    "weaponType": "redBreath",
    "bst": 168,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Tiki:_Beachside_Scion"
  }),
  "Titania": new Unit({
    "name": "Titania",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Titania:_Mighty_Mercenary"
  }),
  "Tobin": new Unit({
    "name": "Tobin",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Tobin:_The_Clueless_One"
  }),
  "Ursula": new Unit({
    "name": "Ursula",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Ursula:_Blue_Crow"
  }),
  "Valter": new Unit({
    "name": "Valter",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Valter:_Dark_Moonstone"
  }),
  "BH-Veronica": new Unit({
    "name": "BH-Veronica",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2020,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Veronica:_Brave_Princess"
  }),
  "Virion": new Unit({
    "name": "Virion",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Virion:_Elite_Archer"
  }),
  "Walhart": new Unit({
    "name": "Walhart",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Walhart:_The_Conqueror"
  }),
  "Wrys": new Unit({
    "name": "Wrys",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1970,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": false,
    "link": "Wrys:_Kindly_Priest"
  }),
  "Xander": new Unit({
    "name": "Xander",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Xander:_Paragon_Knight"
  }),
  "PA-Xander": new Unit({
    "name": "PA-Xander",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Xander:_Dancing_Knight"
  }),
  "S-Xander": new Unit({
    "name": "S-Xander",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Xander:_Spring_Prince"
  }),
  "SS-Xander": new Unit({
    "name": "SS-Xander",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true,
    "limited": false,
    "link": "Xander:_Student_Swimmer"
  }),
  "Zelgius": new Unit({
    "name": "Zelgius",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 174,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true,
    "limited": false,
    "link": "Zelgius:_Jet-Black_General"
  }),
  "Zephiel": new Unit({
    "name": "Zephiel",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 168,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false,
    "limited": true,
    "link": "Zephiel:_The_Liberator"
  })
}