const units = {
  "Abel": new Unit({
    "name": "Abel",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Alfonse": new Unit({
    "name": "Alfonse",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "HF-Alfonse": new Unit({
    "name": "HF-Alfonse",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Alm": new Unit({
    "name": "Alm",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Amelia": new Unit({
    "name": "Amelia",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 173,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Anna": new Unit({
    "name": "Anna",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Arden": new Unit({
    "name": "Arden",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ares": new Unit({
    "name": "Ares",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Arthur": new Unit({
    "name": "Arthur",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Arvis": new Unit({
    "name": "Arvis",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Athena": new Unit({
    "name": "Athena",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ayra": new Unit({
    "name": "Ayra",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Azama": new Unit({
    "name": "Azama",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Azura": new Unit({
    "name": "Azura",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "NY-Azura": new Unit({
    "name": "NY-Azura",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "PA-Azura": new Unit({
    "name": "PA-Azura",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Barst": new Unit({
    "name": "Barst",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Bartre": new Unit({
    "name": "Bartre",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Berkut": new Unit({
    "name": "Berkut",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Beruka": new Unit({
    "name": "Beruka",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Black-Knight": new Unit({
    "name": "Black-Knight",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Boey": new Unit({
    "name": "Boey",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Caeda": new Unit({
    "name": "Caeda",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "B-Caeda": new Unit({
    "name": "B-Caeda",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Cain": new Unit({
    "name": "Cain",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Camilla": new Unit({
    "name": "Camilla",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY-Camilla": new Unit({
    "name": "NY-Camilla",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "S-Camilla": new Unit({
    "name": "S-Camilla",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "SS-Camilla": new Unit({
    "name": "SS-Camilla",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Camus": new Unit({
    "name": "Camus",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Canas": new Unit({
    "name": "Canas",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Catria": new Unit({
    "name": "Catria",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Catria": new Unit({
    "name": "S-Catria",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Cecilia": new Unit({
    "name": "Cecilia",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Celica": new Unit({
    "name": "Celica",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "FH-Celica": new Unit({
    "name": "FH-Celica",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B-Charlotte": new Unit({
    "name": "B-Charlotte",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Cherche": new Unit({
    "name": "Cherche",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Chrom": new Unit({
    "name": "Chrom",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY-Chrom": new Unit({
    "name": "NY-Chrom",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "K-Chrom": new Unit({
    "name": "K-Chrom",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Chrom": new Unit({
    "name": "S-Chrom",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Clair": new Unit({
    "name": "Clair",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Clarine": new Unit({
    "name": "Clarine",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Clarisse": new Unit({
    "name": "Clarisse",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Clive": new Unit({
    "name": "Clive",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Cordelia": new Unit({
    "name": "Cordelia",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Cordelia": new Unit({
    "name": "S-Cordelia",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "B-Cordelia": new Unit({
    "name": "B-Cordelia",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "F-Corrin": new Unit({
    "name": "F-Corrin",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "M-Corrin": new Unit({
    "name": "M-Corrin",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY-Corrin": new Unit({
    "name": "NY-Corrin",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Corrin": new Unit({
    "name": "S-Corrin",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Deirdre": new Unit({
    "name": "Deirdre",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Delthea": new Unit({
    "name": "Delthea",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Donnel": new Unit({
    "name": "Donnel",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Dorcas": new Unit({
    "name": "Dorcas",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Draug": new Unit({
    "name": "Draug",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Effie": new Unit({
    "name": "Effie",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 168,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Eirika": new Unit({
    "name": "Eirika",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "F-Eirika": new Unit({
    "name": "F-Eirika",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Eldigan": new Unit({
    "name": "Eldigan",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Elincia": new Unit({
    "name": "Elincia",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "PA-Elincia": new Unit({
    "name": "PA-Elincia",
    "moveType": "infantry",
    "weaponType": "greenBow",
    "bst": 139,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Elise": new Unit({
    "name": "Elise",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Elise": new Unit({
    "name": "S-Elise",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "LA-Eliwood": new Unit({
    "name": "LA-Eliwood",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Eliwood": new Unit({
    "name": "Eliwood",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ephraim": new Unit({
    "name": "Ephraim",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L-Ephraim": new Unit({
    "name": "L-Ephraim",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Est": new Unit({
    "name": "Est",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Fae": new Unit({
    "name": "Fae",
    "moveType": "infantry",
    "weaponType": "greenBreath",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Faye": new Unit({
    "name": "Faye",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Felicia": new Unit({
    "name": "Felicia",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Finn": new Unit({
    "name": "Finn",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Fir": new Unit({
    "name": "Fir",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Fjorm": new Unit({
    "name": "Fjorm",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Florina": new Unit({
    "name": "Florina",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Frederick": new Unit({
    "name": "Frederick",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 153,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Frederick": new Unit({
    "name": "S-Frederick",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Gaius": new Unit({
    "name": "Gaius",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Gaius": new Unit({
    "name": "S-Gaius",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Genny": new Unit({
    "name": "Genny",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Gerome": new Unit({
    "name": "Gerome",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 161,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Gordin": new Unit({
    "name": "Gordin",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Gray": new Unit({
    "name": "Gray",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Gunnthra": new Unit({
    "name": "Gunnthra",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Gunter": new Unit({
    "name": "Gunter",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Gwendolyn": new Unit({
    "name": "Gwendolyn",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 169,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hana": new Unit({
    "name": "Hana",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hardin": new Unit({
    "name": "Hardin",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Hawkeye": new Unit({
    "name": "Hawkeye",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hector": new Unit({
    "name": "Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 168,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "LA-Hector": new Unit({
    "name": "LA-Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 173,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "L-Hector": new Unit({
    "name": "L-Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Henry": new Unit({
    "name": "Henry",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "H-Henry": new Unit({
    "name": "H-Henry",
    "moveType": "armor",
    "weaponType": "greenTome",
    "bst": 165,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Hinata": new Unit({
    "name": "Hinata",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hinoka": new Unit({
    "name": "Hinoka",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "BSW-Hinoka": new Unit({
    "name": "BSW-Hinoka",
    "moveType": "flier",
    "weaponType": "bow",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Ike": new Unit({
    "name": "Ike",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B-Ike": new Unit({
    "name": "B-Ike",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L-Ike": new Unit({
    "name": "L-Ike",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Inigo": new Unit({
    "name": "Inigo",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Innes": new Unit({
    "name": "Innes",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Innes": new Unit({
    "name": "S-Innes",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Ishtar": new Unit({
    "name": "Ishtar",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Jaffar": new Unit({
    "name": "Jaffar",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Jagen": new Unit({
    "name": "Jagen",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Jakob": new Unit({
    "name": "Jakob",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "H-Jakob": new Unit({
    "name": "H-Jakob",
    "moveType": "armor",
    "weaponType": "bow",
    "bst": 165,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Jeorge": new Unit({
    "name": "Jeorge",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Joshua": new Unit({
    "name": "Joshua",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Julia": new Unit({
    "name": "Julia",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Julius": new Unit({
    "name": "Julius",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Kagero": new Unit({
    "name": "Kagero",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Kagero": new Unit({
    "name": "S-Kagero",
    "moveType": "flier",
    "weaponType": "dagger",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "F-Kana": new Unit({
    "name": "F-Kana",
    "moveType": "infantry",
    "weaponType": "greenBreath",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "M-Kana": new Unit({
    "name": "M-Kana",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Karel": new Unit({
    "name": "Karel",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Karla": new Unit({
    "name": "Karla",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Katarina": new Unit({
    "name": "Katarina",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Kaze": new Unit({
    "name": "Kaze",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Klein": new Unit({
    "name": "Klein",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "L-Arachel": new Unit({
    "name": "L-Arachel",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Lachesis": new Unit({
    "name": "Lachesis",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Laslow": new Unit({
    "name": "Laslow",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Legault": new Unit({
    "name": "Legault",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Legion": new Unit({
    "name": "Legion",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Leif": new Unit({
    "name": "Leif",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Lene": new Unit({
    "name": "Lene",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Leo": new Unit({
    "name": "Leo",
    "moveType": "cavalry",
    "weaponType": "redTome",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Leo": new Unit({
    "name": "S-Leo",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Leon": new Unit({
    "name": "Leon",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Libra": new Unit({
    "name": "Libra",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Lilina": new Unit({
    "name": "Lilina",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "LA-Lilina": new Unit({
    "name": "LA-Lilina",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Linde": new Unit({
    "name": "Linde",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Linde": new Unit({
    "name": "S-Linde",
    "moveType": "cavalry",
    "weaponType": "dagger",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Linus": new Unit({
    "name": "Linus",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Lissa": new Unit({
    "name": "Lissa",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY-Lissa": new Unit({
    "name": "NY-Lissa",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Lloyd": new Unit({
    "name": "Lloyd",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Lon-qu": new Unit({
    "name": "Lon-qu",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Lucina": new Unit({
    "name": "Lucina",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B-Lucina": new Unit({
    "name": "B-Lucina",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L-Lucina": new Unit({
    "name": "L-Lucina",
    "moveType": "infantry",
    "weaponType": "blueBow",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2320,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Lucina": new Unit({
    "name": "S-Lucina",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Lucius": new Unit({
    "name": "Lucius",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Lukas": new Unit({
    "name": "Lukas",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Luke": new Unit({
    "name": "Luke",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Lute": new Unit({
    "name": "Lute",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Lyn": new Unit({
    "name": "Lyn",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B-Lyn": new Unit({
    "name": "B-Lyn",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "BH-Lyn": new Unit({
    "name": "BH-Lyn",
    "moveType": "cavalry",
    "weaponType": "bow",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L-Lyn": new Unit({
    "name": "L-Lyn",
    "moveType": "infantry",
    "weaponType": "greenBow",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "LA-Lyn": new Unit({
    "name": "LA-Lyn",
    "moveType": "armor",
    "weaponType": "blueTome",
    "bst": 165,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Lyon": new Unit({
    "name": "Lyon",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 152,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Mae": new Unit({
    "name": "Mae",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Maria": new Unit({
    "name": "Maria",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Maribelle": new Unit({
    "name": "Maribelle",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Marisa": new Unit({
    "name": "Marisa",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Marth": new Unit({
    "name": "Marth",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "B-Marth": new Unit({
    "name": "B-Marth",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "M-Marth": new Unit({
    "name": "M-Marth",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 8,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Mathilda": new Unit({
    "name": "Mathilda",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Matthew": new Unit({
    "name": "Matthew",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Merric": new Unit({
    "name": "Merric",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Mia": new Unit({
    "name": "Mia",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Micaiah": new Unit({
    "name": "Micaiah",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2320,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "PA-Micaiah": new Unit({
    "name": "PA-Micaiah",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 139,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Michalis": new Unit({
    "name": "Michalis",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Minerva": new Unit({
    "name": "Minerva",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Mist": new Unit({
    "name": "Mist",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "F-Morgan": new Unit({
    "name": "F-Morgan",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "M-Morgan": new Unit({
    "name": "M-Morgan",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Myrrh": new Unit({
    "name": "Myrrh",
    "moveType": "flier",
    "weaponType": "greenBreath",
    "bst": 167,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Nanna": new Unit({
    "name": "Nanna",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Narcian": new Unit({
    "name": "Narcian",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 6,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Navarre": new Unit({
    "name": "Navarre",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 6,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Nephenee": new Unit({
    "name": "Nephenee",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Niles": new Unit({
    "name": "Niles",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ninian": new Unit({
    "name": "Ninian",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B-Ninian": new Unit({
    "name": "B-Ninian",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 140,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Nino": new Unit({
    "name": "Nino",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "P-Nino": new Unit({
    "name": "P-Nino",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Noire": new Unit({
    "name": "Noire",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Nowi": new Unit({
    "name": "Nowi",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "H-Nowi": new Unit({
    "name": "H-Nowi",
    "moveType": "flier",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Oboro": new Unit({
    "name": "Oboro",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Odin": new Unit({
    "name": "Odin",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ogma": new Unit({
    "name": "Ogma",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Oliver": new Unit({
    "name": "Oliver",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Olivia": new Unit({
    "name": "Olivia",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "PA-Olivia": new Unit({
    "name": "PA-Olivia",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 140,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "F-Olivia": new Unit({
    "name": "F-Olivia",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Olwen": new Unit({
    "name": "Olwen",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "R-Olwen": new Unit({
    "name": "R-Olwen",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Oscar": new Unit({
    "name": "Oscar",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Palla": new Unit({
    "name": "Palla",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Peri": new Unit({
    "name": "Peri",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Priscilla": new Unit({
    "name": "Priscilla",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Raigh": new Unit({
    "name": "Raigh",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Raven": new Unit({
    "name": "Raven",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Rebecca": new Unit({
    "name": "Rebecca",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Reinhardt": new Unit({
    "name": "Reinhardt",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Reinhardt": new Unit({
    "name": "S-Reinhardt",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Rhajat": new Unit({
    "name": "Rhajat",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "F-Grima": new Unit({
    "name": "F-Grima",
    "moveType": "flier",
    "weaponType": "breath",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "M-Grima": new Unit({
    "name": "M-Grima",
    "moveType": "armor",
    "weaponType": "greenBreath",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "F-Robin": new Unit({
    "name": "F-Robin",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 6,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "M-Robin": new Unit({
    "name": "M-Robin",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "SF-Robin": new Unit({
    "name": "SF-Robin",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "NYM-Robin": new Unit({
    "name": "NYM-Robin",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Roderick": new Unit({
    "name": "Roderick",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Roy": new Unit({
    "name": "Roy",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "B-Roy": new Unit({
    "name": "B-Roy",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "LA-Roy": new Unit({
    "name": "LA-Roy",
    "moveType": "cavalry",
    "weaponType": "bow",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Ryoma": new Unit({
    "name": "Ryoma",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L-Ryoma": new Unit({
    "name": "L-Ryoma",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "PA-Ryoma": new Unit({
    "name": "PA-Ryoma",
    "moveType": "infantry",
    "weaponType": "blueBow",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Saber": new Unit({
    "name": "Saber",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Saias": new Unit({
    "name": "Saias",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Saizo": new Unit({
    "name": "Saizo",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Sakura": new Unit({
    "name": "Sakura",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "H-Sakura": new Unit({
    "name": "H-Sakura",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Sanaki": new Unit({
    "name": "Sanaki",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B-Sanaki": new Unit({
    "name": "B-Sanaki",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Selena": new Unit({
    "name": "Selena",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Seliph": new Unit({
    "name": "Seliph",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Serra": new Unit({
    "name": "Serra",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Seth": new Unit({
    "name": "Seth",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Setsuna": new Unit({
    "name": "Setsuna",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Shanna": new Unit({
    "name": "Shanna",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Sharena": new Unit({
    "name": "Sharena",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S-Sharena": new Unit({
    "name": "S-Sharena",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Sheena": new Unit({
    "name": "Sheena",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 169,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Shigure": new Unit({
    "name": "Shigure",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "PA-Shigure": new Unit({
    "name": "PA-Shigure",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 139,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Shiro": new Unit({
    "name": "Shiro",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Siegbert": new Unit({
    "name": "Siegbert",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Sigurd": new Unit({
    "name": "Sigurd",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 159,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Soleil": new Unit({
    "name": "Soleil",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Sonya": new Unit({
    "name": "Sonya",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Sophia": new Unit({
    "name": "Sophia",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Soren": new Unit({
    "name": "Soren",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Sothe": new Unit({
    "name": "Sothe",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Stahl": new Unit({
    "name": "Stahl",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Subaki": new Unit({
    "name": "Subaki",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Sully": new Unit({
    "name": "Sully",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Sumia": new Unit({
    "name": "Sumia",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Tailtiu": new Unit({
    "name": "Tailtiu",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Takumi": new Unit({
    "name": "Takumi",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "F-Takumi": new Unit({
    "name": "F-Takumi",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY-Takumi": new Unit({
    "name": "NY-Takumi",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 152,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "S-Takumi": new Unit({
    "name": "S-Takumi",
    "moveType": "flier",
    "weaponType": "bow",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Tana": new Unit({
    "name": "Tana",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S-Tana": new Unit({
    "name": "S-Tana",
    "moveType": "flier",
    "weaponType": "redTome",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Tharja": new Unit({
    "name": "Tharja",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "B-Tharja": new Unit({
    "name": "B-Tharja",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "NY-Tharja": new Unit({
    "name": "NY-Tharja",
    "moveType": "armor",
    "weaponType": "redTome",
    "bst": 165,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "A-Tiki": new Unit({
    "name": "A-Tiki",
    "moveType": "infantry",
    "weaponType": "redBreath",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Y-Tiki": new Unit({
    "name": "Y-Tiki",
    "moveType": "infantry",
    "weaponType": "redBreath",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "SA-Tiki": new Unit({
    "name": "SA-Tiki",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "SY-Tiki": new Unit({
    "name": "SY-Tiki",
    "moveType": "flier",
    "weaponType": "redBreath",
    "bst": 168,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Titania": new Unit({
    "name": "Titania",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Tobin": new Unit({
    "name": "Tobin",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ursula": new Unit({
    "name": "Ursula",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Valter": new Unit({
    "name": "Valter",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Virion": new Unit({
    "name": "Virion",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Walhart": new Unit({
    "name": "Walhart",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Wrys": new Unit({
    "name": "Wrys",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Xander": new Unit({
    "name": "Xander",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "PA-Xander": new Unit({
    "name": "PA-Xander",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "S-Xander": new Unit({
    "name": "S-Xander",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "SS-Xander": new Unit({
    "name": "SS-Xander",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Zelgius": new Unit({
    "name": "Zelgius",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 174,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Zephiel": new Unit({
    "name": "Zephiel",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 168,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  })
}