const units = {
  "Abel": new Unit({
    "name": "Abel",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Alfonse": new Unit({
    "name": "Alfonse",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "HF!Alfonse": new Unit({
    "name": "HF!Alfonse",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Alm": new Unit({
    "name": "Alm",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Amelia": new Unit({
    "name": "Amelia",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 173,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Anna": new Unit({
    "name": "Anna",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 0,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Arden": new Unit({
    "name": "Arden",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ares": new Unit({
    "name": "Ares",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Arthur": new Unit({
    "name": "Arthur",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Arvis": new Unit({
    "name": "Arvis",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Athena": new Unit({
    "name": "Athena",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ayra": new Unit({
    "name": "Ayra",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Azama": new Unit({
    "name": "Azama",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Azura": new Unit({
    "name": "Azura",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "NY!Azura": new Unit({
    "name": "NY!Azura",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "PA!Azura": new Unit({
    "name": "PA!Azura",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 149,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Barst": new Unit({
    "name": "Barst",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Bartre": new Unit({
    "name": "Bartre",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Berkut": new Unit({
    "name": "Berkut",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 4,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Beruka": new Unit({
    "name": "Beruka",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Black Knight": new Unit({
    "name": "Black Knight",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Boey": new Unit({
    "name": "Boey",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Caeda": new Unit({
    "name": "Caeda",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "B!Caeda": new Unit({
    "name": "B!Caeda",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Cain": new Unit({
    "name": "Cain",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Camilla": new Unit({
    "name": "Camilla",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY!Camilla": new Unit({
    "name": "NY!Camilla",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "S!Camilla": new Unit({
    "name": "S!Camilla",
    "moveType": "flier",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "SS!Camilla": new Unit({
    "name": "SS!Camilla",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Camus": new Unit({
    "name": "Camus",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 3,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Canas": new Unit({
    "name": "Canas",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Catria": new Unit({
    "name": "Catria",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S!Catria": new Unit({
    "name": "S!Catria",
    "moveType": "cavalry",
    "weaponType": "blueTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Cecilia": new Unit({
    "name": "Cecilia",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Celica": new Unit({
    "name": "Celica",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "FH!Celica": new Unit({
    "name": "FH!Celica",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B!Charlotte": new Unit({
    "name": "B!Charlotte",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Cherche": new Unit({
    "name": "Cherche",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Chrom": new Unit({
    "name": "Chrom",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY!Chrom": new Unit({
    "name": "NY!Chrom",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "K!Chrom": new Unit({
    "name": "K!Chrom",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S!Chrom": new Unit({
    "name": "S!Chrom",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Clair": new Unit({
    "name": "Clair",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Clarine": new Unit({
    "name": "Clarine",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Clarisse": new Unit({
    "name": "Clarisse",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 5,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Clive": new Unit({
    "name": "Clive",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Cordelia": new Unit({
    "name": "Cordelia",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S!Cordelia": new Unit({
    "name": "S!Cordelia",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "B!Cordelia": new Unit({
    "name": "B!Cordelia",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "F!Corrin": new Unit({
    "name": "F!Corrin",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "M!Corrin": new Unit({
    "name": "M!Corrin",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "NY!Corrin": new Unit({
    "name": "NY!Corrin",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S!Corrin": new Unit({
    "name": "S!Corrin",
    "moveType": "flier",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Deirdre": new Unit({
    "name": "Deirdre",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Delthea": new Unit({
    "name": "Delthea",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Donnel": new Unit({
    "name": "Donnel",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Dorcas": new Unit({
    "name": "Dorcas",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Draug": new Unit({
    "name": "Draug",
    "moveType": "armor",
    "weaponType": "sword",
    "bst": 169,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Effie": new Unit({
    "name": "Effie",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 168,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Eirika": new Unit({
    "name": "Eirika",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "F!Eirika": new Unit({
    "name": "F!Eirika",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 144,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Eldigan": new Unit({
    "name": "Eldigan",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 154,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Elincia": new Unit({
    "name": "Elincia",
    "moveType": "flier",
    "weaponType": "sword",
    "bst": 156,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Elise": new Unit({
    "name": "Elise",
    "moveType": "cavalry",
    "weaponType": "staff",
    "bst": 145,
    "hasSuperBoon": false,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S!Elise": new Unit({
    "name": "S!Elise",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "LA!Eliwood": new Unit({
    "name": "LA!Eliwood",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Eliwood": new Unit({
    "name": "Eliwood",
    "moveType": "cavalry",
    "weaponType": "sword",
    "bst": 155,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Ephraim": new Unit({
    "name": "Ephraim",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L!Ephraim": new Unit({
    "name": "L!Ephraim",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Est": new Unit({
    "name": "Est",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Fae": new Unit({
    "name": "Fae",
    "moveType": "infantry",
    "weaponType": "greenBreath",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Faye": new Unit({
    "name": "Faye",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 154,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Felicia": new Unit({
    "name": "Felicia",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Finn": new Unit({
    "name": "Finn",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Fir": new Unit({
    "name": "Fir",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Fjorm": new Unit({
    "name": "Fjorm",
    "moveType": "infantry",
    "weaponType": "lance",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Florina": new Unit({
    "name": "Florina",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Frederick": new Unit({
    "name": "Frederick",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 153,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S!Frederick": new Unit({
    "name": "S!Frederick",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 149,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Gaius": new Unit({
    "name": "Gaius",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S!Gaius": new Unit({
    "name": "S!Gaius",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Genny": new Unit({
    "name": "Genny",
    "moveType": "infantry",
    "weaponType": "staff",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 1870,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Gerome": new Unit({
    "name": "Gerome",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 161,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Gordin": new Unit({
    "name": "Gordin",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Gray": new Unit({
    "name": "Gray",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Gunnthra": new Unit({
    "name": "Gunnthra",
    "moveType": "cavalry",
    "weaponType": "greenTome",
    "bst": 145,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Gunter": new Unit({
    "name": "Gunter",
    "moveType": "cavalry",
    "weaponType": "axe",
    "bst": 150,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Gwendolyn": new Unit({
    "name": "Gwendolyn",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 169,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hana": new Unit({
    "name": "Hana",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hardin": new Unit({
    "name": "Hardin",
    "moveType": "armor",
    "weaponType": "lance",
    "bst": 175,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Hawkeye": new Unit({
    "name": "Hawkeye",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hector": new Unit({
    "name": "Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 168,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "LA!Hector": new Unit({
    "name": "LA!Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 173,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "L!Hector": new Unit({
    "name": "L!Hector",
    "moveType": "armor",
    "weaponType": "axe",
    "bst": 174,
    "hasSuperBoon": true,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Henry": new Unit({
    "name": "Henry",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "H!Henry": new Unit({
    "name": "H!Henry",
    "moveType": "armor",
    "weaponType": "greenTome",
    "bst": 165,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Hinata": new Unit({
    "name": "Hinata",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Hinoka": new Unit({
    "name": "Hinoka",
    "moveType": "flier",
    "weaponType": "lance",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "BSW!Hinoka": new Unit({
    "name": "BSW!Hinoka",
    "moveType": "flier",
    "weaponType": "bow",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Ike": new Unit({
    "name": "Ike",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 158,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "B!Ike": new Unit({
    "name": "B!Ike",
    "moveType": "infantry",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2280,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "L!Ike": new Unit({
    "name": "L!Ike",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 163,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": true,
    "seasonnal": false,
    "only5Star": true
  }),
  "Inigo": new Unit({
    "name": "Inigo",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 140,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Innes": new Unit({
    "name": "Innes",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "S!Innes": new Unit({
    "name": "S!Innes",
    "moveType": "flier",
    "weaponType": "axe",
    "bst": 162,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Ishtar": new Unit({
    "name": "Ishtar",
    "moveType": "infantry",
    "weaponType": "blueTome",
    "bst": 151,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Jaffar": new Unit({
    "name": "Jaffar",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Jagen": new Unit({
    "name": "Jagen",
    "moveType": "cavalry",
    "weaponType": "lance",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Jakob": new Unit({
    "name": "Jakob",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "H!Jakob": new Unit({
    "name": "H!Jakob",
    "moveType": "armor",
    "weaponType": "bow",
    "bst": 165,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "Jeorge": new Unit({
    "name": "Jeorge",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Joshua": new Unit({
    "name": "Joshua",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 1,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Julia": new Unit({
    "name": "Julia",
    "moveType": "infantry",
    "weaponType": "greenTome",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Julius": new Unit({
    "name": "Julius",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2220,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Kagero": new Unit({
    "name": "Kagero",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 148,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "S!Kagero": new Unit({
    "name": "S!Kagero",
    "moveType": "flier",
    "weaponType": "dagger",
    "bst": 150,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": true,
    "only5Star": true
  }),
  "F!Kana": new Unit({
    "name": "F!Kana",
    "moveType": "infantry",
    "weaponType": "greenBreath",
    "bst": 163,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "M!Kana": new Unit({
    "name": "M!Kana",
    "moveType": "infantry",
    "weaponType": "blueBreath",
    "bst": 164,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 2,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Karel": new Unit({
    "name": "Karel",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 157,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Karla": new Unit({
    "name": "Karla",
    "moveType": "infantry",
    "weaponType": "sword",
    "bst": 162,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Katarina": new Unit({
    "name": "Katarina",
    "moveType": "infantry",
    "weaponType": "redTome",
    "bst": 147,
    "hasSuperBoon": true,
    "maxSp": 2220,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": true
  }),
  "Kaze": new Unit({
    "name": "Kaze",
    "moveType": "infantry",
    "weaponType": "dagger",
    "bst": 151,
    "hasSuperBoon": false,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  }),
  "Klein": new Unit({
    "name": "Klein",
    "moveType": "infantry",
    "weaponType": "bow",
    "bst": 148,
    "hasSuperBoon": true,
    "maxSp": 2170,
    "maxMerge": 10,
    "isLegendary": false,
    "seasonnal": false,
    "only5Star": false
  })
}